
export interface Employee {
  id: string; // Internal unique ID generated by the system (e.g., INTERNAL-timestamp-random)
  employeeId: string; // User-defined employee ID, should be unique (e.g., EMP001)
  name: string;
  faceImageUri: string; // Data URI of the registered face photo
  department?: string;
  createdAt: string; // ISO date string
}

export interface AttendanceRecord {
  id: string; // Unique record ID
  employeeId: string; // Refers to Employee.id (internal unique ID)
  employeeName: string; // Denormalized for convenience
  checkInTime?: string; // ISO date string
  checkOutTime?: string; // ISO date string
  date: string; // YYYY-MM-DD format
  status: 'Checked-In' | 'Checked-Out' | 'Absent';
  manuallyEdited?: boolean;
  notes?: string;
}

// For realTimeFaceRecognition GenAI flow
export interface EmployeeRecognitionData {
  employeeId: string; // Refers to Employee.id (internal unique ID)
  faceEncoding: string; // This will be the faceImageUri for the GenAI flow
}
